ALTER TYPE "ExpenseStatus" ADD VALUE IF NOT EXISTS 'DRAFT';
ALTER TYPE "ExpenseStatus" ADD VALUE IF NOT EXISTS 'PENDING';
ALTER TABLE "Expense" ADD COLUMN IF NOT EXISTS "vatEstimated" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "Expense" ADD COLUMN IF NOT EXISTS "note" TEXT;
