CREATE TYPE "VatRegime" AS ENUM ('ENCASHMENT', 'DEBIT');
ALTER TABLE "Company" ADD COLUMN IF NOT EXISTS "vatRegime" "VatRegime" NOT NULL DEFAULT 'ENCASHMENT';
ALTER TABLE "BankTransaction" ADD COLUMN IF NOT EXISTS "vatAmount" DECIMAL(12,2);
ALTER TABLE "BankTransaction" ADD COLUMN IF NOT EXISTS "vatEstimated" BOOLEAN NOT NULL DEFAULT false;
